### PR TITLE
fix(#2763): 修复 legend-filter 在view中行为错误

### LINKED ISSUE #2763: legend-filter在view中行为错误
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/bold-fast-uquku?file=/index.js)

### Steps to reproduce
Screen Recording 2020-08-20 at 21 01 01 2020-08-20 21_04_52

点击图例，蓝绿两色折线不能按正常逻辑隐藏/显示，正常行为应该同[此demo](https://antv-g2.gitee.io/zh/examples/line/basic#curved)。

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | MacOS Catalina 10.15.6 (19G73) |
| Browser | Chrome 84.0.4147.135 |

---
本例与官方demo的区别在于，数据是在Chart中的一个View里的，而非直接在Chart中。个人尝试在源码中定位错误，奈何个人太菜，无果，故来此求大神赐教。

### PR DESCRIPTION
**Pull request by Me-Momo**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Description of change

closed #2763

### CODE REVIEW

**Review by hustcc — APPROVED** [review]

File: src/util/legend.ts [hunk 1]
```diff
@@ -55,7 +55,12 @@ export function getLegendItems(
       const value = scale.invert(scaleValue);
 
       // 通过过滤图例项的数据，来看是否 unchecked
-      const unchecked = view.filterFieldData(field, [{ [field]: value }]).length === 0;
+      let unchecked = view.filterFieldData(field, [{ [field]: value }]).length === 0;
+      each(view.views, (subView) => {
+        if (!subView.filterFieldData(field, [{ [field]: value }]).length) {
+          unchecked = true;
```
Comment (simaQ) [inline src/util/legend.ts:61]: 是不是要 return false; 下，是只要有一个满足就设置为 true 然后不需要循环吗
