### PR TITLE
fix: set appropriate value of zIndex.

### LINKED ISSUE #264: tooltip z-index
将z-index:999 是出于什么考虑的。如果页面滚动的话，tooltip将会在Header上面。

### PR DESCRIPTION
**Pull request by simaQ**
Closed #264 
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

### CODE REVIEW

File: src/component/guide/arc.js [hunk 1]
```diff
@@ -14,7 +14,6 @@ class Arc extends Base {
        * @type {String}
        */
       type: 'arc',
-      zIndex: 15,
```
Comment (OPY-bbt) [inline src/component/guide/arc.js:17]: test
