### PR TITLE
fix: update legend component inferring strategies

### LINKED ISSUE #4904: 【v5】散点图 size 绑定数据时，color 设置固定颜色无法作图
## 问题描述

**只设置 size 通道，正常**
image

**异常情况**
image

## 期望结果

size 绑定数据时，color 可以设置某个固定颜色

## 如何重现

官方示例修改
```javascript
import { Chart } from '@antv/g2';

const chart = new Chart({
  container: 'container',
  theme: 'classic',
  2autoFit: true,
});

chart
  .point()
  .data({
    type: 'fetch',
    value:
      'https://gw.alipayobjects.com/os/basement_prod/6b4aa721-b039-49b9-99d8-540b3f87d339.json',
  })
  .encode('x', 'height')
  .encode('y', 'weight')
  .encode('size', 'gender')
  .encode('color', 'red');
  

chart.render();
```

## 额外信息

* G2 5.0.3

### PR DESCRIPTION
**Pull request by Aarebecca**
通过比例尺推断组件添加了额外的规则：
1. 如果比例尺全为常量比例尺，则不推断图例
2. 如果组件为连续图例，其颜色比例尺必须指定domain

fixed #4904

### CODE REVIEW

File: src/runtime/component.ts [hunk 1]
```diff
@@ -311,6 +311,17 @@ function inferLegendComponentType(
       for (const [componentType, accords] of strategy) {
         for (const { option, combination } of options) {
           if (accords.some((accord) => isEqual(sort(accord), sort(option)))) {
+            // extra rule
```
Comment (hustcc) [inline src/runtime/component.ts:314]: 找个地方写上清晰的注释，说明 strategy 主要是考虑哪些情况下，有什么 component。

**Comment by pearmini** [comment]
> 如果组件为连续图例，其颜色比例尺必须指定domain

为啥需要这个限制？

File: src/runtime/component.ts (hunk 1 above)
Comment (hustcc) [reply src/runtime/component.ts:314]: 代码注释 + 讨论区。

**Comment by Aarebecca** [comment]
> > 如果组件为连续图例，其颜色比例尺必须指定domain
> 
> 为啥需要这个限制？

没有颜色的话或者单一颜色，绘制连续比例尺应该没有意义

File: src/runtime/component.ts [hunk 2]
```diff
@@ -311,6 +311,17 @@ function inferLegendComponentType(
...
+            // 1. combination can't all be constant scale
+            // 2. when componentType is continuous, color scale must has domain
+            if (combination.every((scale) => scale.type === 'constant'))
+              continue;
+            if (componentType.toLowerCase().includes('continuous')) {
+              const colorScale = combination.find(
+                (scale) => scale.name === 'color',
+              );
+              if (!colorScale || !colorScale.domain?.length) continue;
+            }
```
Comment (pearmini) [inline src/runtime/component.ts:324]: scale.domain 都是没有值的话，为啥会是连续比例尺？有具体的案例可以看看吗？

**Review by pearmini — CHANGES_REQUESTED** [review]

**Comment by Aarebecca** [comment]
## 图例组件推断关系

> 例子：
> 当前比例尺组合为： color 通道为离散比例尺，shape 通道为 常数比例尺
> 则会匹配上第规则 27，因此可以使用分类图例

> 如果比例尺组合为：shape 通道为离散比例尺，size 通道为 常数比例尺
> 则没有可匹配的规则，因此当前比例尺组合不会推断出图例

### legendCategory
1. color-`discrete` opacity-`discrete` shape-`discrete` size-`constant`
2. color-`discrete` opacity-`constant` shape-`discrete` size-`constant`
3. color-`discrete` opacity-`discrete` shape-`constant` size-`constant`
4. color-`discrete` opacity-`constant` shape-`constant` size-`constant`
5. color-`constant` opacity-`discrete` shape-`discrete` size-`constant`
6. color-`constant` opacity-`constant` shape-`discrete` size-`constant`
7. color-`constant` opacity-`discrete` shape-`constant` size-`constant`
8. color-`discrete` shape-`discrete` size-`constant`
9. color-`discrete` opacity-`discrete` shape-`discrete`
10. color-`discrete` opacity-`discrete` size-`constant`
11. color-`discrete` opacity-`constant` shape-`discrete`
12. color-`discrete` opacity-`constant` size-`constant`
13. color-`discrete` shape-`constant` size-`constant`
14. color-`discrete` opacity-`discrete` shape-`constant`
15. color-`discrete` opacity-`constant` shape-`constant`
16. color-`constant` shape-`discrete` size-`constant`
17. color-`constant` opacity-`discrete` shape-`discrete`
18. color-`constant` opacity-`discrete` size-`constant`
19. color-`constant` opacity-`constant` shape-`discrete`
20. color-`constant` opacity-`constant` size-`constant`
21. color-`constant` shape-`constant` size-`constant`
22. color-`constant` opacity-`discrete` shape-`constant`
23. color-`discrete` shape-`discrete`
24. color-`discrete` size-`constant`
25. color-`discrete` opacity-`discrete`
26. color-`discrete` opacity-`constant`
27. color-`discrete` shape-`constant`
28. color-`constant` shape-`discrete`
29. color-`constant` size-`constant`
30. color-`constant` opacity-`discrete`
31. color-`constant` opacity-`constant`
32. color-`constant` shape-`constant`
33. color-`discrete`
34. color-`constant`
### legendContinuousSize
1. color-`continuous` opacity-`continuous` size-`continuous`
2. color-`constant` opacity-`continuous` size-`continuous`
3. color-`continuous` size-`continuous`
4. color-`constant` size-`continuous`
### legendContinuousBlockSize
1. color-`distribution` opacity-`distribution` size-`distribution`
2. color-`distribution` size-`distribution`
### legendContinuousBlock
1. color-`distribution` opacity-`continuous`
2. color-`distribution`
### legendContinuous
1. color-`continuous` opacity-`continuous`
2. color-`continuous`

File: src/runtime/component.ts (hunk 1 above)
Comment (Aarebecca) [reply src/runtime/component.ts]: 更新到  `src/component/constant.ts` 了

File: src/runtime/component.ts (hunk 2 above)
Comment (Aarebecca) [reply src/runtime/component.ts]: 更新了下

```ts
function bodyPointScatterPlot(): G2Spec {
  return {
    type: 'point',
    data: {
      type: 'fetch',
      value: 'data/body.json',
    },
    encode: {
      x: 'height',
      y: 'weight',
      size: 'weight',
      color: 'red',
    },
  };
}
```

colorScale 为常数比例尺
sizeScale 为连续比例尺

现在绘制为连续图例的形式

bodyPointScatterPlot

**Review by pearmini — APPROVED** [review]

**Comment by hustcc** [comment]
> 图例组件推断关系

这个我们周一一起筛查一下，究竟哪些是需要显示图例的。比如：单测截图中的但颜色的 size 图例，就感觉默认不太合理，虽然用户通过 api 都可以调整，但是最好还是默认就相对来说是好用好看的。
