### PR TITLE
fix: when color field === x field, tooltip crosshair'bug

### LINKED ISSUE #1248: interval hover size error
* **G2 Version**: 3.5.2
* **Platform**: Windows 10  Chrome
* **Mini Showcase(like screenshots)**: 
image

* **CodePen Link**: https://jsfiddle.net/yx1foLpm/1/

Hover background should contain two bars.
FYI. using `color('name')` works fine, any value other than `name` goes wrong.

### PR DESCRIPTION
**Pull request by hustcc**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fixed #1248 

### 💡 Background and solution

根据特定的情况，打补丁修复。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] All tests pass and/or benchmarks are included
- [x] Commit message follows commit guidelines
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by hustcc** [comment]
自动 diff 的不是很好。截图 diff：

image

**Comment by dxq613** [comment]
我只能说这个补丁打的很有艺术。。。后面人改的时候会懵的。

File: src/chart/controller/tooltip.js [hunk 1]
```diff
@@ -396,9 +396,18 @@ class TooltipController {
...
-              const tmpPoint = geom.findPoint(point, obj);
-              if (tmpPoint) {
+
+            // 打补丁解决 bug: https://github.com/antvis/g2/issues/1248
+            // 当 interval 对应的 color 和 x 字段相同的时候，items 取值逻辑不一样
+            // 这种情况下，每一个 x 字段分成一组
+            const xScale = geom.getXScale();
+            const colorAttr = geom.getAttr('color');
+            const colorField = colorAttr ? colorAttr.field : undefined;
+            if (type === 'interval' && xScale.field === colorField) {
```
Comment (dxq613) [inline src/chart/controller/tooltip.js]: 这个地方其实还可以再加个条件， 是否 dodge了，经常有这种写法会命中你这个条件

```js
chart.interval().position('x*y').color('x');
```
