### PR TITLE
fix(label): fix label dom leak, fixed #1213

### LINKED ISSUE #1213: label使用html模式渲染时，repaint、render没有销毁
G2 Version: 3.4.10
Platform:
Mini Showcase(like screenshots):
radar
CodePen Link: https://riddle.alibaba-inc.com/riddles/80596d7f

### PR DESCRIPTION
**Pull request by hustcc**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

> **等 https://github.com/antvis/component/pull/68 合并并发包之后，这个 issue 和单测 就会 pass，这个 pr 仅仅补充单测。**

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] All tests pass and/or benchmarks are included
- [x] Commit message follows commit guidelines
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

* fixed #1213 
* fixed #1494

### CODE REVIEW

File: test/bugs/issue-1213-spec.js [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+      forceFit: true
+    });
+
+    chart.coord('polar', {
+      radius: 0.8
+    });
+
+    chart.axis('rain', {
+      label: {
+        position: 'buttom',
```
Comment (simaQ) [inline test/bugs/issue-1213-spec.js]: buttom 是啥👻？
